/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.github.cschen1205.ess.engine.RuleInferenceEngine;

import java.util.AbstractMap;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;

import se.BaseDeConocimiento;
import se.Hechos;

import javax.swing.*;

/**
 * @author Ian Lehmann
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.setTitle("Diagnostico Dengue/Covid-19");
        this.checks = new HashMap<>();

        checks.put(Hechos.dolorAbdominal, boxAbsominal);
        checks.put(Hechos.dolorArticular, boxArticular);
        checks.put(Hechos.dolorCabeza, boxCabeza);
        checks.put(Hechos.congestionNasal, boxCongestionNasal);
        checks.put(Hechos.contactoCOVID, boxContactoCovid);
        checks.put(Hechos.debilidadGeneralziada, boxDebilidad);
        checks.put(Hechos.diarrea, boxDiarrea);
        checks.put(Hechos.dificultadRespirar, boxDiffRespirar);
        checks.put(Hechos.sangradoEncias, boxEncias);
        checks.put(Hechos.erupcionCutanea, boxErupcionCutanea);
        checks.put(Hechos.escalofrios, boxEscalofrios);
        checks.put(Hechos.fatiga, boxFatiga);
        checks.put(Hechos.fiebre, boxFiebre);
        checks.put(Hechos.dolorGarganta, boxGarganta);
        checks.put(Hechos.dolorMuscular, boxMuscular);
        checks.put(Hechos.sangradoNariz, boxNariz);
        checks.put(Hechos.nauseas, boxNauseas);
        checks.put(Hechos.dolorOjos, boxOcular);
        checks.put(Hechos.dolorPecho, boxPecho);
        checks.put(Hechos.perdidaGusto, boxPerdidaGusto);
        checks.put(Hechos.perdidaOlfato, boxPerdidaOlfato);
        checks.put(Hechos.sangradoPiel, boxPiel);
        checks.put(Hechos.sarpullido, boxSarpullido);
        checks.put(Hechos.tos, boxTos);
        checks.put(Hechos.vomito, boxVomitos);
        checks.put(Hechos.zonaRiesgo, boxZonaDengue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxMuscular = new javax.swing.JCheckBox();
        boxAbsominal = new javax.swing.JCheckBox();
        boxOcular = new javax.swing.JCheckBox();
        boxArticular = new javax.swing.JCheckBox();
        boxGarganta = new javax.swing.JCheckBox();
        boxPecho = new javax.swing.JCheckBox();
        boxCabeza = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boxEncias = new javax.swing.JCheckBox();
        boxPiel = new javax.swing.JCheckBox();
        boxNariz = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        boxDiarrea = new javax.swing.JCheckBox();
        boxNauseas = new javax.swing.JCheckBox();
        boxVomitos = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        boxDiffRespirar = new javax.swing.JCheckBox();
        boxCongestionNasal = new javax.swing.JCheckBox();
        boxTos = new javax.swing.JCheckBox();
        boxPerdidaOlfato = new javax.swing.JCheckBox();
        boxPerdidaGusto = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        boxZonaDengue = new javax.swing.JCheckBox();
        boxContactoCovid = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        boxFiebre = new javax.swing.JCheckBox();
        boxFatiga = new javax.swing.JCheckBox();
        boxDebilidad = new javax.swing.JCheckBox();
        boxEscalofrios = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        boxErupcionCutanea = new javax.swing.JCheckBox();
        boxSarpullido = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado_diagnostico = new javax.swing.JTextArea();
        botDiagnosticar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Tipo de Dolores");

        boxMuscular.setText("Muscular");

        boxAbsominal.setText("Abdominal");

        boxOcular.setText("Ocular");

        boxArticular.setText("Articular");

        boxGarganta.setText("Garganta");

        boxPecho.setText("Pecho");

        boxCabeza.setText("Cabeza");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxMuscular))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxAbsominal))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxOcular))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxArticular))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxGarganta))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(boxCabeza)
                                                        .addComponent(boxPecho))))
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(7, 7, 7)
                                .addComponent(boxMuscular)
                                .addGap(3, 3, 3)
                                .addComponent(boxAbsominal)
                                .addGap(3, 3, 3)
                                .addComponent(boxOcular)
                                .addGap(3, 3, 3)
                                .addComponent(boxArticular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxGarganta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxPecho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                                .addComponent(boxCabeza)
                                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Tipo de Sangrado");

        boxEncias.setText("Encias");

        boxPiel.setText("Piel");

        boxNariz.setText("Nariz");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel2))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxEncias))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxPiel))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxNariz)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxEncias)
                                .addGap(3, 3, 3)
                                .addComponent(boxPiel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                                .addComponent(boxNariz)
                                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Problemas Digestivos");

        boxDiarrea.setText("Diarrea");

        boxNauseas.setText("Nauseas");

        boxVomitos.setText("Vomitos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxDiarrea))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxNauseas))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxVomitos)))
                                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7)
                                .addComponent(boxDiarrea)
                                .addGap(3, 3, 3)
                                .addComponent(boxNauseas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                                .addComponent(boxVomitos)
                                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Problemas Respiratorios");

        boxDiffRespirar.setText("Dificultad para respirar");

        boxCongestionNasal.setText("Congestion Nasal");

        boxTos.setText("Tos");

        boxPerdidaOlfato.setText("Perdida de Olfato");

        boxPerdidaGusto.setText("Perdida de Gusto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel4))
                                        .addComponent(boxDiffRespirar)
                                        .addComponent(boxCongestionNasal)
                                        .addComponent(boxTos)
                                        .addComponent(boxPerdidaOlfato)
                                        .addComponent(boxPerdidaGusto))
                                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)
                                .addComponent(boxDiffRespirar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxCongestionNasal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxTos)
                                .addGap(3, 3, 3)
                                .addComponent(boxPerdidaOlfato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxPerdidaGusto)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Zona de Riesgo");

        boxZonaDengue.setText("Zona de Contagio de Dengue");

        boxContactoCovid.setText("Contacto Estrecho con Alguien con COVID-19");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxZonaDengue))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxContactoCovid)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxZonaDengue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                                .addComponent(boxContactoCovid)
                                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Otros Sintomas");

        boxFiebre.setText("Fiebre");

        boxFatiga.setText("Fatiga");

        boxDebilidad.setText("Debilidad Generalizada");

        boxEscalofrios.setText("Escalofrios");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(jLabel6))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxFiebre))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxFatiga))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxDebilidad))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxEscalofrios)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addGap(7, 7, 7)
                                .addComponent(boxFiebre)
                                .addGap(3, 3, 3)
                                .addComponent(boxFatiga)
                                .addGap(3, 3, 3)
                                .addComponent(boxDebilidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                                .addComponent(boxEscalofrios)
                                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Sintomas de Piel");

        boxErupcionCutanea.setText("Erupcion Cutanea");

        boxSarpullido.setText("Sarpullido");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel7))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxErupcionCutanea))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(boxSarpullido)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(7, 7, 7)
                                .addComponent(boxErupcionCutanea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                                .addComponent(boxSarpullido)
                                .addContainerGap())
        );

        resultado_diagnostico.setColumns(20);
        resultado_diagnostico.setRows(5);
        jScrollPane1.setViewportView(resultado_diagnostico);

        botDiagnosticar.setText("Diagnosticar");
        botDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDiagnosticarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botDiagnosticar)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(botDiagnosticar)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {

        //Cargar los hechos
        checks
                .entrySet()
                .stream()
                .filter(entry -> entry.getValue().isSelected())
                .map(selectedEntries -> new AbstractMap.SimpleEntry(selectedEntries.getKey(),"si"))
                .forEach(fact -> _rie.addFact(fact.getKey().toString(),fact.getValue().toString()));


        _rie.infer();

        boolean COVID = false;
        boolean DENGUE = false;

        if (_rie.getFactsAboutVariable(Hechos.COVID).size() > 0) {
            COVID = true;
        }
        if (_rie.getFactsAboutVariable(Hechos.dengue).size() > 0) {
            DENGUE = true;
        }

        String diagnostico;
        if (COVID || DENGUE) {
            diagnostico = "Posible diagnostico: ";
            if (COVID)
                diagnostico += " COVID";

            if (DENGUE)
                diagnostico += ", Dengue";
        } else {
            diagnostico = "No se pudo determinar el diagnostico.";
        }

        resultado_diagnostico.setText(diagnostico);

        boxAbsominal.setSelected(false);
        boxArticular.setSelected(false);
        boxCabeza.setSelected(false);
        boxCongestionNasal.setSelected(false);
        boxContactoCovid.setSelected(false);
        boxDebilidad.setSelected(false);
        boxDiarrea.setSelected(false);
        boxDiffRespirar.setSelected(false);
        boxEncias.setSelected(false);
        boxErupcionCutanea.setSelected(false);
        boxEscalofrios.setSelected(false);
        boxFatiga.setSelected(false);
        boxFiebre.setSelected(false);
        boxGarganta.setSelected(false);
        boxMuscular.setSelected(false);
        boxNariz.setSelected(false);
        boxNauseas.setSelected(false);
        boxOcular.setSelected(false);
        boxPecho.setSelected(false);
        boxPerdidaGusto.setSelected(false);
        boxPerdidaOlfato.setSelected(false);
        boxPiel.setSelected(false);
        boxSarpullido.setSelected(false);
        boxTos.setSelected(false);
        boxVomitos.setSelected(false);
        boxZonaDengue.setSelected(false);

        _rie = BaseDeConocimiento.getRules(true);

    }//GEN-LAST:event_botDiagnosticarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botDiagnosticar;
    private javax.swing.JCheckBox boxAbsominal;
    private javax.swing.JCheckBox boxArticular;
    private javax.swing.JCheckBox boxCabeza;
    private javax.swing.JCheckBox boxCongestionNasal;
    private javax.swing.JCheckBox boxContactoCovid;
    private javax.swing.JCheckBox boxDebilidad;
    private javax.swing.JCheckBox boxDiarrea;
    private javax.swing.JCheckBox boxDiffRespirar;
    private javax.swing.JCheckBox boxEncias;
    private javax.swing.JCheckBox boxErupcionCutanea;
    private javax.swing.JCheckBox boxEscalofrios;
    private javax.swing.JCheckBox boxFatiga;
    private javax.swing.JCheckBox boxFiebre;
    private javax.swing.JCheckBox boxGarganta;
    private javax.swing.JCheckBox boxMuscular;
    private javax.swing.JCheckBox boxNariz;
    private javax.swing.JCheckBox boxNauseas;
    private javax.swing.JCheckBox boxOcular;
    private javax.swing.JCheckBox boxPecho;
    private javax.swing.JCheckBox boxPerdidaGusto;
    private javax.swing.JCheckBox boxPerdidaOlfato;
    private javax.swing.JCheckBox boxPiel;
    private javax.swing.JCheckBox boxSarpullido;
    private javax.swing.JCheckBox boxTos;
    private javax.swing.JCheckBox boxVomitos;
    private javax.swing.JCheckBox boxZonaDengue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado_diagnostico;

    private final Map<String, JCheckBox> checks;
    // End of variables declaration//GEN-END:variables

    private RuleInferenceEngine _rie = BaseDeConocimiento.getRules(true);
}
